create database applicants;
create table datas (
	Surname varchar (30),
	Firstname varchar (30),
	Middlename varchar (30),
	Nameextension varchar (30),
	Bday date,
	Placeofbirth varchar (30),
	Sex varchar (30),
	Civil_Status varchar (30),
	Height float,
	Weight float,
	Bloodtype varchar (30),
	GSIS varchar (30) primary key,
	PAGIBIG varchar (30),
	PhilHealth varchar (30),
	SSS varchar (30),
	TIN varchar (30),
	EmployeeNo varchar (30),
	Citizenship varchar (30),
	country varchar (30),
	Residence_add varchar(100),
	Permanent_add varchar(100),
	Telephone varchar (30),
	Mobile varchar (30),
	Email varchar (30),
	Spouse_surname varchar (30),
	Spouse_first varchar (30),
	Spouse_middle varchar (30),
	Spouse_nameextension varchar (30),
	Spouse_occupation varchar (30),
	Spouse_employer varchar (30),
	Spouse_businessaddress varchar (30),
	Spouse_telephone varchar (30),
	Father_surname varchar (30),
	Father_first varchar (30),
	Father_middle varchar (30),
	Father_nameextension varchar (30),
	Mother_maiden varchar (30),
	Mother_surname varchar (30),
	Mother_first varchar (30),
	Mother_middle varchar (30),
	Child1 varchar (30),
	Child2 varchar (30),
	Child3 varchar (30),
	Child4 varchar (30),
	Child5 varchar (30),
	ChildBirthDate1 date,
	ChildBirthDate2 date,
	ChildBirthDate3 date,
	ChildBirthDate4 date,
	ChildBirthDate5 date,
	Elem_name varchar(30),
	Elem_basicEd varchar(30),
	Elem_attendance varchar(30),
	Elem_highestlevel varchar(30),
	Elem_yrgraduated varchar(30),
	Elem_honorscholar varchar(30),
	Second_name varchar(30),
	Second_basicEd varchar(30),
	Second_attendance varchar(30),
	Second_highestlevel varchar(30),
	Second_yrgraduated varchar(30),
	Second_honorscholar varchar(30),
	Voc_name varchar(30),
	Voc_coursedegree varchar(30),
	Voc_attendance varchar(30),
	Voc_highestlevel varchar(30),
	Voc_yrgraduated varchar(30),
	Voc_honorscholar varchar(30),
	College_name varchar(30),
	College_coursedegree varchar(30),
	College_attendance varchar(30),
	College_highestlevel varchar(30),
	College_yrgraduated varchar(30),
	College_honorscholar varchar(30),
	Grad_name varchar(30),
	Grad_coursedegree varchar(30),
	Grad_attendance varchar(30),
	Grad_highestlevel varchar(30),
	Grad_yrgraduated varchar(30),
	Grad_honorscholar varchar(30)
);

create table education(
	EdID varchar(30),
	Lvl varchar(30) primary key
);
